set (TE_GLRENDERAPI_INC_NOFILTER
	"TeGLRenderAPIPrerequisites.h"
	"TeGLRenderAPI.h"
)

set (TE_GLRENDERAPI_SRC_NOFILTER
	"TeGLRenderAPI.cpp"
)

source_group ("" FILES ${TE_GLRENDERAPI_SRC_NOFILTER} ${TE_GLRENDERAPI_INC_NOFILTER})

set (TE_GLRENDERAPI_SRC
	${TE_GLRENDERAPI_INC_NOFILTER}
	${TE_GLRENDERAPI_SRC_NOFILTER}
)